POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json

{
    "email": "user6@mail.com",
    "pass1":"hi5"
}
###

POST http://127.0.0.1:5000/api/signup HTTP/1.1
content-type: application/json

{
    "email": "user8@mail.com",
    "pass1":"zil",
    "pass2":"zil",
    "isCollege":false
}